//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace borrower_NET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BM_DBEntities : DbContext
    {
        public BM_DBEntities()
            : base("name=BM_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BorrowersTb> BorrowersTbs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UsersTb> UsersTbs { get; set; }

        public System.Data.Entity.DbSet<borrower_NET.Models.User> Users { get; set; }

        public System.Data.Entity.DbSet<borrower_NET.Models.Borrower> Borrowers { get; set; }
    }
}
