//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace borrower_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersTb()
        {
            this.BorrowersTbs = new HashSet<BorrowersTb>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string Pincode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowersTb> BorrowersTbs { get; set; }
    }
}
